# Generated by Django 4.0 on 2021-12-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PW_House', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('date_accessed', models.DateField()),
                ('date_added', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Image_Model',
        ),
    ]
