# Generated by Django 4.0 on 2021-12-08 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PW_House', '0002_sources_delete_image_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sources',
            new_name='sourceTable',
        ),
    ]
